# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alphasubcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='productimage'),
        ),
    ]
