# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ps_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.alphasubcat'),
        ),
    ]
