# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_product_p_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userac',
            name='user_email',
            field=models.CharField(default='not available', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
