# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_cart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userac',
            name='user_b_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userac',
            name='user_s_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
