# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alphasubcat',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_name', models.CharField(blank=True, max_length=100, null=True)),
                ('as_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategories')),
            ],
        ),
    ]
