# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_auto_20160310_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_discription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
