# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_order_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wish_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
                ('ou_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.userac')),
            ],
        ),
    ]
