# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagee',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, upload_to='productimage')),
                ('pp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product')),
            ],
        ),
    ]
