# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagee',
            name='ps_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminpanel.alphasubcat'),
            preserve_default=False,
        ),
    ]
