# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_remove_imagee_ps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='productimage')),
                ('alpha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.alphasubcat')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.categories')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategories')),
            ],
        ),
    ]
