# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_home_page_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('produ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.product', unique=True)),
                ('user', models.ManyToManyField(to='adminpanel.userac')),
            ],
        ),
    ]
