# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_auto_20160331_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='productimage'),
        ),
    ]
